#图片存储路径
IMAGE_PATH: upload


server:
  port: 9010
spring:
  application:
    name: taotao-manager-web
  http:
    multipart:
      max-file-size: 10MB
  freemarker:
    suffix: .html

eureka:
  client:
    service-url:
      defaultZone: http://user:password@localhost:9009/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}





