server:
  port: 9015

REDIS_ITEM_KEY: REDIS_ITEM
REDIS_ITEM_EXPIRE: 18000

spring:
  application:
    name: taotao-search-service
  #数据库连接
  datasource:
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/taotao?useSSL=false&characterEncoding=utf-8
    username: wking
    password: king
  #redis TODO 更换host
  redis:
    host: localhost
    port: 6379
  #rabbitMQ TODO 更换host
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    publisher-confirms: true
    virtual-host: /
#mybaits配置
mybatis:
  type-aliases-package: top.kylewang.taotao.pojo
#eureka
eureka:
  client:
    service-url:
      defaultZone: http://user:password@localhost:9009/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}