#首页大广告位的内容分类id
AD1_CONTENT_CID: 89
AD1_WIDTH: 670
AD1_WIDTH_B: 550
AD1_HEIGHT: 240
AD1_HEIGHT_B: 240


server:
  port: 9013
spring:
  application:
    name: taotao-portal-web
  mvc:
    view:
      suffix: .jsp
      prefix: /WEB-INF/jsp/

eureka:
  client:
    service-url:
      defaultZone: http://user:password@localhost:9009/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}





